### ISSUE TITLE
User needs

### ISSUE THREAD

**Issue by Eric-Charpentier** [canada-ca/Open_First_Whitepaper#100]
Hi,

When I read the introduction, I noticed that the User Needs portion was a bit thin. I think that it is extremely important to make sure that everyone understands that the user must come first. Should we consider adding a section on UX development? While it doesn't pertain to open source development directly, it is certainly in the same philosophy and has a direct link to the goals outlined in the Whitepaper.

**Comment by smellems** [comment]
Hi Eric,

UX development will probably better fit in the digital playbook being developed on Github also:
https://github.com/canada-ca/digital-playbook-guide-numerique

We do want to mention the importance of user needs when selecting OSS and open standards.  Feel free to propose changes to the introduction.  I'm looking for ways to improve it

**Comment by gcharest** [comment]
I agree with @smellems here in that the choice of the solution definitely needs to be done with UX in mind. However, I'd rather we need to keep the scope of the white paper on topic 

The playbook will indeed cover that aspect so I suggest that we refer to it in the white paper instead of developing a section for it.
