### ISSUE TITLE
Please add Open Platforms section so we can declare our preferred platforms

### ISSUE THREAD

**Issue by VvonF** [canada-ca/Open_First_Whitepaper#18]

**Comment by sboots** [comment]
Hey @VvonF! Just a caveat - rather than having a section for specific tech platforms (which would always be changing over time) it might be better to keep it more focused on the "why" and "how" rather than specific "what platforms" etc. Similar to international examples like the [US CIO Playbook](https://playbook.cio.gov/#play13), which has a bunch of useful strategies but doesn't list specific tech products to use or not use.

At some point (maybe outside of the scope of the whitepaper) it would be a cool exercise to list a bunch of promising / useful / already being used open source platforms to recommend to teams, but that might be something to place in a separate document or guidance product.

**Comment by lisafast** [comment]
@sboots makes some great points that @steve-h and I support. Rather than getting into specifying platforms, technologies, languages etc., teams should focus on understanding the problem before narrowing in on solutions. That solution may be in a favorite list, or may not (and government has a tendency to view any list as "mandatory" even when it's not). As the team designs an architecture, they may find that existing open code they want to build upon demands a particular platform.

**Comment by mgifford** [comment]
I do think that providing some examples can help, but also really don't want people looking at this to see it is an exclusive list. There is also just so much open source code out there, that anything beyond an example isn't much use.  I was doing a quick search earlier today for 18F for web crawling tools that could be used to scan departmental sites and find broken links. There are just so many out there.  

The trick is to find one that works, has the features that you need and that you can build on.  After you've got that, there definitely needs to be a central place that government can go to to look at future crawlers.  No need to begin the whole process from scratch for every department.  Good to find ways to encourage more collaboration within and between governments.

**Comment by smellems** [comment]
I was thinking of adding the preferred software, platforms, stacks, standards, .. in the related existing sections.

Examples: preferred OSS for CMS, Case management, APM, CRM, ERP, ..  Also preferred OSS Dev stacks, Infrastructure, Monitoring, ..  Of course preferred open standards.

Maybe it could be "Common" solutions for GC.  We make recommendations but you are free to pick to pick any solutions, as long as it aligns with the "open" principles and open standards.

The idea is that we can focus the work of the GC on a few "preferred" solutions (that will evolve) to better invest in those communities.  It's also a guide for departments and agencies when looking for solutions on what others are using that may already meet certain things, like security accreditations.

**Comment by RussellMcOrmond** [comment]
I know some will disagree, but I'd prefer government focused on motivations and methodologies for interacting with software communities rather than specific software projects.  What is preferred for projects if ephemeral, and government changes slowly so you don't want to be stuck with inferior software merely because it was best-of-breed at some moment in the past.  While we may have some younger agile thinkers participating in this specific project, this is not the norm within large bureaucratic structures (with Government only being one such large structure -- this is not an anti-government comment).


Higher level thoughts....

Have you all read "Code and Other Laws of Cyberspace" by Lawrence Lessig? http://codev2.cc/

Using the US context he talks about east-coast code (Referencing the US federal government, and government policy) and east-coast code (Referencing California's silicon valley and software).   He writes mostly about how software code regulates our lives, but the thinking can be applied in other ways.

Example:

If software implements government policy, should it not be seen as a "translation" of the government policy from one language to another and be as open and accountable as the "English" and "French" versions of the policy?   In this context it could be suggested that using sole-source software that is not adequately publicly disclosed is effectively government corruption, rather than thought of as a legitimate acquisition option for government.

I've done many consulting jobs in Government, and the fact that software "procurement" was in a separate budget item from consulting was always a problem -- it meant that proprietary vendor's fees could be "protected" from being transferred to more efficient Open Source consulting or staffing.  (Example was a previous series of long-term contracts with Agriculture Canada where ESRI procurement funding was guaranteed, but we were never able to consult commercially with the Open Source Geospacial people working in Ottawa).

Software shouldn't be thought of as if it were a product that is "procured", but as policy which is adopted.  Governments interact with many other governments and NGOs to share policy ideas and work collaboratively on them -- they don't tend to send policy needs to an RFP process to be "procured" from an unaccountable and non-transparent private sector entity.   No matter what the sector of the collaborators that government uses for software-code/policy, the results should always be open and transparent.  Private sector is often the most appropriate sector for collaboration, but the licensing and other restrictions some private sector entities attempt to apply to the results of projects should never be accepted if that would be at the expense of core government policy goals.


This may all fit into the "Culture" section of the paper, but I believe that higher-level policy goals should be the focus rather than documenting the preferred project-of-the-month.

**Comment by mgifford** [comment]
Quick correction "East-coast code (Referencing the US federal government, and government policy) and **West**-coast code (Referencing California's silicon valley and software)."

Also, as much as I'd like to have my favorite library listed (cough, cough, [Drupal](https://www.drupal.org/) ), I totally support @RussellMcOrmond point.

Having something like this in the Culture space would be great.

**Comment by sboots** [comment]
Seconding @RussellMcOrmond 's point - that's mostly what I would be nervous about as well:

> What is preferred for projects if ephemeral, and government changes slowly so you don't want to be stuck with inferior software merely because it was best-of-breed at some moment in the past.

Interpreting a "here are examples of promising open source projects you can use!" as, "here is the official mandate that you must only use these specific projects" would be a non-optimal outcome.

**Comment by goatsweater** [comment]
Even if there was some kind of line that says “this is not an exhaustive list” people will generally default to not looking past that list if for no other reason than it means extra work, and they have a deadline. Some minor examples of a product when highlighting a principle can be good. Taking it as far as a list, or even a detailed example could end up pushing everyone in a direction we don’t necessarily mean to send them in.

**Comment by nschonni** [comment]
I think particular software, even general stacks, should be left out of an "policy"-like documents. Technical and recommendations are generally better of in guidance documents that can be "refreshed" much easier than a "policy".

**Comment by Acasovan** [comment]
Great discussion here! I think it's important to note that the goal of this whitepaper is to collect ideas that will help us determine a strategy and then a policy on open source. While I agree, our policy (and probably strategy) will not prescribe what specific tools to use, we have to keep in mind that this doc is for us to also have a stronger understanding of open source use within the GC so that we can make the best decisions on all fronts. Part of that is an inventory. As such, I've added a section on open platforms as @VvonF  has requested to try and track this information. As the lead of this whitepaper, it will be easier for me to manage if all the info is in one place, however, I will leave this issue open so that the conversation can continue.
