### ISSUE TITLE
Contractual committments associated with **using** OSS

### ISSUE THREAD

**Issue by plantarum** [canada-ca/Open_First_Whitepaper#77]
The open source software page includes the following under risks:

> The ease and no-cost option of downloading OSS from the internet, and instantly installing it, can create an attractive proposition for employees to side-step procurement processes altogether. This creates two problems: **first, employees may contractually commit the company or government organization to the terms of the software licence without management even becoming aware of this fact;**

This particular page is referring to *using* software, not *reusing code*. In this context, the idea of a contractual commitment imposed on software users is inaccurate, and will inflame the risk-adverse instincts of our managers. There is no contractual commitment, real or implied, by simply using Firefox or LibreOffice. We need to be very careful about using language that will create the impression of hidden legal dangers where there are none.

It would be really useful to have a clearer explanation of what the point of this whitepaper is. At the moment, it still feels like it's an attempt to cover all aspects of using, writing, and distributing OSS, for users, developers, and managers. If we do in fact want to cover all that ground in one document, we need to be really clear about which sections apply to which topics and for which audiences.

**Comment by smellems** [comment]
Thanks!  Your right we should change the language.

Would this be better?
`first, employees would (could?) accept the terms of the software licence without management even becoming aware of this fact;`

or
`first, employees may be using software without management even becoming aware of this fact;`

but then it's the same as `second, losing track of what software is running on employee workstations makes systems security management more difficult.`

The original goal for the whitepaper was to inform a GC strategy on open Standards and OSS.  That's still my goal :smile:  But some sections are long and probably too detailed..

**Comment by RussellMcOrmond** [comment]
Back in 2009, Public Services and Procurement Canada did an RFI on "No Charge Licensed Software (NCLS)".  (I point to the RFI and my submission at http://www.digital-copyright.ca/node/5013 ).

One of the issues discussed at the time was that while FLOSS licenses didn't create obligations on the mere use of software, many non-FLOSS licenses did.  This was true whether the software was "no charge" (royalty free) or royalty-bearing.  Part of the concern of creating an RFI that combined FLOSS and non-FLOSS was that this would cause confusion, given being royalty-free or royalty-bearing wasn't the important distinction.


The suggestion at the time was to have a list of government lawyer approved licenses for software (FLOSS or non-FLOSS) to be used in government, as well as indications of what government employees could do beyond use for the less restrictive licenses (IE: clarity on what obligations, if any, exist when allowed derivatives are distributed).

Unfortunately I didn't see any followup from this policy proposal.   It is important, however, to not raise this as an issue with FLOSS as it is only an issue with non-FLOSS.   Listing this reduction in liability as a benefit of FLOSS is appropriate, given risk averse public servants should already have been following "open first" in order to reduce the increased legal risks associated with the use of non-FLOSS.

Note: Not allowing obligations for the mere use of the software is part of the FSF's definition of Free Software, and the OSI's definition of Open Source.   If an obligation from the use of the software exists, then the software doesn't qualify as FLOSS.

**Comment by plantarum** [comment]
Well said, @RussellMcOrmond . The original wording suggests that FOSS carries an increased risk of ensnaring the government in nasty contract complications compared to non-FOSS, when the opposite is actually true. I think that section should be removed entirely:

> The ease and no-cost option of downloading OSS from the internet, and instantly installing it, can create an attractive proposition for employees to side-step procurement processes altogether. As a consequence, IT staff may lose track of what software is running on employee workstations, making systems security management more difficult. [ and dropping the final sentence of the paragraph ]

Even this may be overstating the case. We aren't permitted admin access to our computers, so I can't install *any* software without a support ticket under normal circumstances. (i.e., ignoring the administration of Linux computers, for which separate approval for admin access is a necessity for use in analysis)

**Comment by mgifford** [comment]
With the GPL 2 it is pretty clear that the use is free, but that there are restrictions on distribution. The restriction is that the distributed work carries the GPL license. I don't see this being a big problem for open government though contributing back to the open source community is a critical part of seeing that it remain vibrant & healthy. Without distribution there are no conditions of use.

**Comment by Acasovan** [comment]
Can you guys suggest these changes via pull request? All good points. Working on organizing a licence workshop in the new year.

**Comment by smellems** [comment]
I made the proposed changes.  Thanks @plantarum @RussellMcOrmond
