### ISSUE TITLE
Open Source Code - Security Classification Guidelines

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/Open_First_Whitepaper#83]
It would be extremely helpful to either have a statement regarding the classification of source code being unclassified, or some guidance on how to determine when your source code is considered protected in the white paper, or some supporting documentation.

We are currently running into an issue where we are being told that an APK should be considered protected b because it can be reverse engineered and with the source code available, vulnerabilities into our network could be found.

I'm concerned that unknown potential vulnerabilities being enough justification to consider something protected could prevent us from being able to open source any of our software.

**Comment by obrien-j** [comment]
Feel free to put your ITSec people in touch with me, or with CSE's ITS Client Services team.

I don't currently speak for @cse_cst but can work with @smellems to draft up what I consider to be a reasonable position on this, and pass it over to them for review. 

Risk aversion like this is why I personally feel we need a blanket 'open source all the things' directive within the government, with very clear and centrally managed exceptions... 

Refer to the two links below for a very well balanced take on the topic. It is my hope that we get to this point.

https://www.gov.uk/government/publications/open-source-guidance/security-considerations-when-coding-in-the-open
&
https://www.gov.uk/government/publications/open-source-guidance/when-code-should-be-open-or-closed

**Comment by mgifford** [comment]
Sounds like if people are trying to make software Protected B that they are coding with legacy "Security by Obscurity" approaches. If modern best practices are followed there isn't a risk of protected data being exposed through reverse engineering open source code.

**Comment by Acasovan** [comment]
Hey! There have been lots of questions re: Security related to open source. I'm happy to report that our Chief Security Officer and his team are working on this now, and we will have a section dedicated to it in the very near future (but probably after the holidays)!

**Comment by smellems** [comment]
@Acasovan there are sections on security in the whitepaper under
- [OSS Benefits](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/3_Open_Source_Software.md#security)
- [OSS Risks](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/3_Open_Source_Software.md#security-1)
It's about if OSS is secure (security flaws) for use. We don't currently talk about classification of source code when publishing open source code.

We should probably add more under [Open Source Code Best Practices](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/4_Open_Source_Code.md#best-practices)

**Comment by ptd-tbs** [comment]
The Treasury Board [Directive on Departmental Security Management (DDSM)](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=16579) defines protected information as one that “may qualify for an exemption or exclusion under the Access to Information Act or the Privacy Act because its disclosure would reasonably be expected to compromise the non-national interest.”

In order for source code to potentially be deemed protected, it would have to contain any of the following information:

- Clause 13(1) of the [Access to Information Act](http://laws-lois.justice.gc.ca/eng/acts/A-1/): Information obtained in confidence
- 14: Information about federal-provincial affairs
- 15: Information about international affairs and defence
- 16: Information about law enforcement and investigations 
- 17: Information about the safety of individuals
- 18: information about the economic interests of Canada
- 19: Personal information
- 20: Third party information 
- 21: Advice about certain aspects of operations of government
- 22: Information about testing procedures, tests, and audits
- 23: Information that is subject to solicitor-client privilege
- 24: Information that is subject to statutory prohibitions
- 68: Certain types of information held by the Canadian Broadcasting Corporation and Atomic Energy of Canada Limited
- 69: Confidences of the Queen’s Privy Council for Canada 

It is highly unlikely that developers would intentionally include such information in their source code. As a result, the proposed categorization for the confidentiality of source code is considered unclassified unless the developer has included, inadvertently or otherwise, information that falls under the [exemptions](http://laws-lois.justice.gc.ca/eng/acts/a-1/page-3.html#h-10) and [exclusions](http://laws-lois.justice.gc.ca/eng/acts/a-1/page-10.html#h-29) of the [Access to Information Act](http://laws-lois.justice.gc.ca/eng/acts/A-1/) as listed above. Where feasible, this information should be removed from the source code to increase the ability for code to be shared.

Some security considerations to keep in mind when developing software:

- Keep sensitive data such as credentials secure and separate from source code.
- Avoid storing keys and other sensitive material in systems not approved for that purpose.
- Code reviews increase the likelihood of catching bugs, security vulnerabilities, and reduces the risk of committing sensitive data.
- Implement controls sufficient to prevent unauthorized or inadvertent changes.

**Comment by obrien-j** [comment]
LGTM!

**Comment by smellems** [comment]
@ptd-tbs Thanks for this!  I added it under [Open Source Code Best Practices](https://github.com/canada-ca/Open_First_Whitepaper/blob/master/4_Open_Source_Code.md#best-practices)

@CalvinRodo will close this issue, let us know if this works for you

**Comment by CalvinRodo** [comment]
I hope it works for me, I guess I'll find out soon enough.

**Comment by Keith-Douglas** [comment]
This handles the confidentiality. What about the integrity?

**Comment by goatsweater** [comment]
Testing in this context does not refer to unit tests. The testing would be for testing procedures, so for example if the software was being used to detect fraud you may not want to release certain aspects of the algorithms in use.

In most cases, software, its associated tests, and documentation should be released.

**Comment by obrien-j** [comment]
@Keith-Douglas Depends on deep the rabbit-hole you want to go on the integrity front. 

Git as a vcs offers a fairly significant integrity guarantee through it's tree structure and commit log history. Most implementations github, gitlab, etc, also offer audit logs on top of this underlying layer, as well as offering 2FA guarantees if desired.

Some have gone down the route of individual signing of commits as well if you're really in a space where you need that level of integrity from keyboard to deployment.

Did you have any specific concerns?

**Comment by Keith-Douglas** [comment]
> @Keith-Douglas Depends on deep the rabbit-hole you want to go on the integrity front.
> 
> Git as a vcs offers a fairly significant integrity guarantee through it's tree structure and commit log history. Most implementations github, gitlab, etc, also offer audit logs on top of this underlying layer, as well as offering 2FA guarantees if desired.
> 
> Some have gone down the route of individual signing of commits as well if you're really in a space where you need that level of integrity from keyboard to deployment.
> 
> Did you have any specific concerns?

Thanks for the reply, but I think this is backwards: one sets up those sorts of things based on BNS, hence also data classification, not the other way around. If the expectation is that although SC is unclassified it is still medium integrity (say) then a lot of those things would be necessary. I think of, for example, the social system allowing various classes of people to participate in contributing to an OS project with changes, etc. (So I would want a personnel screening control, various instances of "role specific security awareness", and then of course auditing, input validation, etc. in lots of places. But there are places where the official classification makes for direct consequences: For example: one uses different encryption standards according to ITSP 40.111 depending on data integrity. (And confidentiality, which suggests a high-water mark here, maybe?) That said, I would do it a lot anyway.

@goatsweater : As for the testing, may I ask on what basis you are concluding that? (I would want an official discussion for that topic and the other in any case.)

**Comment by CalvinRodo** [comment]
@Keith-Douglas In regards to @goatsweater comment on testing, I'm not quite sure we need an official discussion for that topic, while I did bring that specific statement up with TBS since I was concerned that folks would see that and incorrectly come to the conclusion that Unit Testing and End to End testing was considered Protected B. I think we just need to take a bit of a common sense approach to determine that those should not be considered PB, at least they shouldn't be if the source code itself is considered unclassified. 

For instance if end to end tests such as those done using tools like Selenium, Cypress.io, or any other tool that allows you to programatically interface with a site then that implies the the interfaces to our sites, and services either the gui or APIs that are usually public facing are considered protected B and well I don't know how we would deal with that and still provide services to citizens. 

If unit tests are considered PB (or higher) then that would raise the question of why the source code itself is considered unclassified since all unit tests are is code that invokes methods that are already considered unclassified, and since presumably other parts of the code base are doing just that, what makes these invocations protected and those invocations unclassified? 

As for your concerns about integrity of the code, I think most of your concerns would be covered through as @obrien-j said the actual mechanics of the source control itself, provide a fairly high level of integrity assuming that the owners of that repository are performing the bare minimum of due diligence, (Code review, CI/CD pipelines,  2FA). These are things that as you said should be done regardless of the integrity of the source code. 

**Side Note:** I would ask that you either refrain from domain specific acronyms or at least spell them out firstly in a public forum such as this and would ask even in internal discussions as well.  Even though I've been a developer in the government for 15 years this is the first I've heard of the acronym BNS and had to dig it up in some GoC documentation. For those who are curious **BNS** refers to [Business need for Security.](https://www.canada.ca/en/government/system/digital-government/modern-emerging-technologies/cloud-services/government-canada-security-control-profile-cloud-based-it-services.html#toc2-1)

**Comment by goatsweater** [comment]
As @CalvinRodo pointed out, a common sense approach to the idea of applying the testing criteria of ATIP to unit tests should generally lead to the conclusion that the unit tests fall in the same category as the code itself. Arguably it should be easier to make an unclassified test of a protected bit of source code if the test were merely calling service end points.

Having as much of the code open as possible (including tests) was a topic of discussion when the whitepaper was being drafted, and included review/input from multiple groups in TBS & CSE to ensure that the guidance in the document didn’t fall on the wrong side of other policies or directives. The Open Source Advisory Council had a rules working group looking into this and other issues similar, which is where the current guidance in the document comes from. Not trying to say a new/continuing discussion isn’t warranted, just wanted to let you know that formal discussions were held.
